version: "3"
services:
  osm-service0:
    image: openplannerteam/routeable-tiles-api
    container_name: routeable-tiles0
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - /storage:/var/app/db/
      - /var/services/routeable-tiles0/logs:/var/app/logs
    networks:
      - osm-service
  osm-service1:
    image: openplannerteam/routeable-tiles-api
    container_name: routeable-tiles1
    restart: always
    ports:
      - "5001:5000"
    volumes:
      - /storage:/var/app/db/
      - /var/services/routeable-tiles1/logs:/var/app/logs
    networks:
      - osm-service

networks:
  osm-service:
    driver: bridge
